// End-of-month SIP formula, limits, rounding and generated-example regression.
const fs = require('fs'), vm = require('vm'), assert = require('assert/strict');
const context = { document: { addEventListener() {}, querySelectorAll: () => [], getElementById: () => ({}) }, window: { addEventListener() {} }, console };
vm.createContext(context);
vm.runInContext(fs.readFileSync('script.js', 'utf8'), context);
const definition = vm.runInContext('dynamicToolDefinitions.sip', context);
const values = (monthly = '5000', rate = '12', years = '10') => ({ sipMonthly: monthly, sipAnnualRate: rate, sipYears: years });
const near = (actual, expected) => assert(Math.abs(actual - expected) <= Math.max(1e-6, Math.abs(expected) * 1e-12), `${actual} != ${expected}`);
let checks = 0;
for (const input of [values(), values('1000', '0', '1'), values('10000', '8', '20'), values('5000', '10.5', '10'), values('5000', '12', '1.5'), values('5000', '12', '1.1'), values('0'), values('1000000000', '0', '1'), values('1234.56', '10.5', '2.5')]) {
    const monthly = Number(input.sipMonthly), rate = Number(input.sipAnnualRate) / 1200, months = Number(input.sipYears) * 12;
    const expected = rate === 0 ? monthly * months : monthly * (Math.pow(1 + rate, months) - 1) / rate;
    const result = context.calculateSip(input);
    near(result.invested, monthly * months); near(result.futureValue, expected); near(result.returns, expected - monthly * months);
    assert(!/NaN|Infinity|undefined/.test(JSON.stringify(definition.calculate(input)))); checks++;
}
// Independent monthly recurrence confirms deposits are made after each month's growth.
let balance = 0;
for (let month = 0; month < 120; month++) balance = balance * 1.01 + 5000;
const main = context.calculateSip(values());
near(main.futureValue, balance); near(main.invested, 600000); near(main.returns, balance - 600000);
assert(Math.abs(main.futureValue - balance * 1.01) > 10000, 'Must not use beginning-of-month deposits');
assert.equal(definition.calculate(values()).display, '₹11,50,193');
assert.equal(definition.calculate(values('1000', '0', '1')).display, '₹12,000');
near(context.calculateSip(values('1000', '0', '1')).returns, 0);
near(context.calculateSip(values('5000', '0.0000000001', '10')).futureValue, 600000 + 5000 * 120 * 119 / 2 * (0.0000000001 / 1200));
checks += 3;
for (const key of ['sipMonthly', 'sipAnnualRate', 'sipYears']) {
    for (const bad of ['', ' ', '-1', 'abc', '10oops', 'Infinity', 'NaN', '1e309']) {
        assert.throws(() => context.calculateSip({ ...values(), [key]: bad })); checks++;
    }
}
for (const bad of [values('1000000001'), values('5000', '100.01'), values('5000', '12', '100.01'), values('5000', '12', '0'), values('5000', '12', '0.01'), values('1000000000', '100', '100')]) {
    assert.throws(() => context.calculateSip(bad)); checks++;
}
const html = fs.readFileSync('sip-calculator/index.html', 'utf8');
assert.match(html, /<h1>SIP Calculator India<\/h1>/);
assert.match(html, /rel="canonical" href="https:\/\/onlinecalmaster.com\/sip-calculator\/"/);
assert(!/name="keywords"/.test(html));
assert(html.includes(definition.help.example), 'Delivered example must be generated by the calculator formula');
for (const amount of [main.invested, main.returns, main.futureValue]) assert(definition.help.example.includes(context.formatSipCurrency(amount)));
assert.match(html, /end of each month/);
assert.match(html, /Past performance does not guarantee future performance/);
assert.match(html, /id="dynamic-sipMonthly"[^>]*value="5000"/);
assert.match(html, /id="dynamic-sipAnnualRate"[^>]*value="12"/);
assert.match(html, /id="dynamic-sipYears"[^>]*value="10"/);
console.log(`${checks} SIP formula/validation cases passed, plus end-of-month recurrence, defaults, Indian formatting and generated-example/SEO checks.`);
console.log(JSON.stringify({ defaultExample: main, scenarioB: context.calculateSip(values('10000', '8', '20')) }, null, 2));
